; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Wl,-u,_printf_float
    -I lib/dw3000/dwt_uwb_driver
    -I lib/dw3000/dwt_uwb_driver/dw3000
    -I lib/dw3000/dwt_uwb_driver/dw3720
    -I lib/dw3000/dwt_uwb_driver/lib/qmath/include
    -I lib/dw3000/port


lib_deps =
    file://lib/dw3000

test_framework = unity
test_speed = 115200
